export enum ApartmentType {
    HOTEL = "HOTEL",
    APARTMENTS = "APARTMENTS",
    RESORT_HOTEL = "RESORT_HOTEL",
    VILLA = "VILLA",
    CHALET = "CHALET",
    COTTAGE = "COTTAGE",
    GLAMPING = "GLAMPING",
    MOTELS = "MOTELS"
}
